#!/bin/bash
#create a new repository on the command line

echo "# utilitats" >> README.md
git init
git add README.md
git commit -m "first commit"
git branch -M main
git remote add origin git@github.com:rclaver/utilitats.git
git push -u origin main
